Python Missing Data & More indexing

In [2]:
import numpy as np
import pandas as pd

In [ ]:
#python uses None to represent arbitary or missing values
vals1 = np.array([1,None,3,4]) #None is an object type
vals1

array([1, None, 3, 4], dtype=object)

In [ ]:
#numpy uses NaN (not a number)
vals2 = np.array([1,np.nan,3,4]) #float
vals2

array([ 1., nan,  3.,  4.])

In [7]:
#when doing arthemtic with NaN the solution will be Nan
print(1+np.nan)
print(1* np.nan)

nan
nan

In [9]:
#Numpy can ignore NaN
np.nansum(vals2) #nanmin, nanmax

np.float64(8.0)

In Pandas

In [ ]:
pd.Series([1, np.nan, 2, None]) #pandas handles both

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [13]:
#pandas converts None to NaN
x = pd.Series(range(2), dtype=int)
print(x)
x[0] = None
print(x)

0    0
1    1
dtype: int64
0    NaN
1    1.0
dtype: float64

In [15]:
#Pandas can detect null data
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
#pretty self explantory
data.dropna()

0        1
2    hello
dtype: object

For dataframes

In [18]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna() #dropna will default remove rows with null values

     0    1  2
1  2.0  3.0  5

In [ ]:
df.dropna(axis = 1) #dropna can also drop columns

   2
0  2
1  5
2  6

In [ ]:
#we can drop rows or columns that contain only null values
df[3] = np.nan
print(df)
print(df.dropna(axis=1, how='all')) #hoow = 'all' drops rows or columns with only null values

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [28]:
#Instead of dropping we can fill with a set value
df.fillna(0)

     0    1  2    3
0  1.0  0.0  2  0.0
1  2.0  3.0  5  0.0
2  0.0  4.0  6  0.0

In [29]:
df.fillna(method='ffill')

C:\Users\aypen\AppData\Local\Temp\ipykernel_34588\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  2.0  4.0  6 NaN

Hierarchial Indexing

In [31]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [ ]:
pop = pd.Series(populations, index=index)
pop #using population as keys

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
#Multi indexing gives us multiple labels for the same value
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [ ]:
pop = pop.reindex(index)
pop #Hierarchial representation

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
print(pop[:, 2010]) #all data in 2010
print(pop['California']) #all the data from California

California    37253956
New York      19378102
Texas         25145561
dtype: int64
2000    33871648
2010    37253956
dtype: int64

In [ ]:
#unstack will convert a series into a data frame - stack is the opposite
pop_df = pop.unstack()
pop_df

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [54]:
#With a multi index we can easily add another column
pop_df.stack
pop_df = pd.DataFrame({'Total' : pop,
                       'Under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

                    Total  Under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [61]:
#Fraction of people under 18
f_u18 = pop_df['Under18'] / pop_df['Total']
f_u18.unstack()

                2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [74]:
#Creating a multi index
data = {('California', 2000) : 33871648,
        ('California', 2010) : 37254956,
        ('New York' , 2000) : 18976457,
        ('New York' , 2010) : 19378102,
        ('Texas' , 2000) : 20851820,
        ('Texas' , 2010) : 25145561}
pop = pd.Series(data) #The series will reckognize it as a multi index

In [90]:
#another way to setup
df = pd.DataFrame(populations, index=[['California', 'California', 'New York', 'New York','Texas', 'Texas'],
                         [2000,2010,2000,2010,2000,2010]],
                         columns=['Populations'])
df

                 Populations
California 2000     33871648
           2010     37253956
New York   2000     18976457
           2010     19378102
Texas      2000     20851820
           2010     25145561

In [ ]:
#We can name the indexs
pop.index.names = ['State', 'Year']
pop

State       year
California  2000    33871648
            2010    37254956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

Using from_product creates all possible cominbations

In [82]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['Year', 'Visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['Heart Rate', 'Temp']],
                                     names=['Subject', 'Test'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

Subject           Bob            Guido              Sue
Test       Heart Rate  Temp Heart Rate  Temp Heart Rate  Temp
Year Visit
2013 1           37.0  36.5       33.0  36.5       43.0  36.4
     2           33.0  35.6       33.0  37.7       35.0  37.4
2014 1           47.0  37.3       30.0  36.9       34.0  37.0
     2           50.0  35.5       25.0  37.4       22.0  35.1

In [80]:
health_data['Guido']

type          HR  Temp
year visit
2013 1      35.0  37.2
     2      36.0  37.5
2014 1      48.0  37.3
     2      49.0  37.4

Indexing and Slicing a Multi index

In [91]:
pop

State       year
California  2000    33871648
            2010    37254956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [102]:
print(pop['California', 2010])
print(pop['California'])
print(pop.loc['California' : 'New York'])
print(pop[pop > 22000000])

37254956
year
2000    33871648
2010    37254956
dtype: int64
State       year
California  2000    33871648
            2010    37254956
New York    2000    18976457
            2010    19378102
dtype: int64
State       year
California  2000    33871648
            2010    37254956
Texas       2010    25145561
dtype: int64

In [103]:
#Can also be applied to data frame
health_data

Subject           Bob            Guido              Sue
Test       Heart Rate  Temp Heart Rate  Temp Heart Rate  Temp
Year Visit
2013 1           37.0  36.5       33.0  36.5       43.0  36.4
     2           33.0  35.6       33.0  37.7       35.0  37.4
2014 1           47.0  37.3       30.0  36.9       34.0  37.0
     2           50.0  35.5       25.0  37.4       22.0  35.1

In [104]:
health_data['Guido', 'Heart Rate']

Year  Visit
2013  1        33.0
      2        33.0
2014  1        30.0
      2        25.0
Name: (Guido, Heart Rate), dtype: float64

Combining datasets

In [47]:
import pandas as pd
import numpy as np
import numexpr

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [ ]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

display('pop.head()', 'areas.head()', 'abbrevs.head()') #head returns n rows

pop.head()
  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

areas.head()
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

abbrevs.head()
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [ ]:
#rank US states by population density

#Start by merging the pop and abbreviation and then drop the abbrev so no duplicate
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')
merged = merged.drop('abbreviation',axis=1)
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [20]:
#check for mismatches
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [27]:
#Puerto Rico doesn't have population data or state entery
merged[merged['population'].isnull()].head()

     state/region     ages  year  population state
1872           PR  under18  1990         NaN   NaN
1873           PR    total  1990         NaN   NaN
1874           PR    total  1991         NaN   NaN
1875           PR  under18  1991         NaN   NaN
1876           PR    total  1993         NaN   NaN

In [ ]:
#Finding which states are null
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [30]:
#Adding states to the abbreviations
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [37]:
#The states are good so we can merge the areas now cause they share similar indexes
final = pd.merge(merged, areas, on='state', how='left')
final.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [38]:
#check for nulls
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [51]:
#Find which state have null area
final['state'][final['area (sq. mi)'].isnull()].unique()#USA
final.dropna(inplace=True)
final.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [89]:
#find the 2010 year
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

    state/region   ages  year  population       state  area (sq. mi)
43            AK  total  2010    713868.0      Alaska       656425.0
51            AL  total  2010   4785570.0     Alabama        52423.0
141           AR  total  2010   2922280.0    Arkansas        53182.0
149           AZ  total  2010   6408790.0     Arizona       114006.0
197           CA  total  2010  37333601.0  California       163707.0

In [90]:
data2010.set_index('state' , inplace=True) #set our index to state
data2010.head()

           state/region   ages  year  population  area (sq. mi)
state
Alaska               AK  total  2010    713868.0       656425.0
Alabama              AL  total  2010   4785570.0        52423.0
Arkansas             AR  total  2010   2922280.0        53182.0
Arizona              AZ  total  2010   6408790.0       114006.0
California           CA  total  2010  37333601.0       163707.0

In [85]:
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending= False).head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64